apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuxt-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nuxt-app
  template:
    metadata:
      labels:
        app: nuxt-app
    spec:
      containers:
        - name: nuxt
          image: tennis0402/test-nuxt-kubernetes:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nuxt-service
spec:
  type: NodePort
  selector:
    app: nuxt-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
